name: Helm CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  helm-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4

    - name: Helm Lint
      run: |
        helm lint ./nginx-webapp

    - name: Helm Template Validation
      run: |
        helm template nginx-webapp ./nginx-webapp

    - name: Helm Package
      run: |
        helm package ./nginx-webapp